NeuroSimulator/urls.py
from django.contrib import admin
from django.urls import include, path
from FuncAtlas import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("FuncAtlas/", include("FuncAtlas.urls"), name="home"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from neuronsimulator import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("neuronsimulator/", include("neuronsimulator.urls")),
]

neuronsimulator/urls.py
from django.urls import path
from neuronsimulator import views

urlpatterns = [
    path("", views.home, name="home"),
    path("load_neurons/", views.load_neurons, name="load_neurons"),
]

neuronsimulator/models.py
from django.db import models


class Neuron(models.Model):
    # store neuron names
    id = models.AutoField(primary_key=True)
    name = models.CharField(
        max_length=10,
        unique=True,
        help_text="The unique name of the worm neuron",
    )

    class Meta:
        verbose_name = "neuron"
        verbose_name_plural = "neurons"
        ordering = ["name"]

    def __str__(self):
        return str(self.name)

neuronsimulator/forms.py
import wormfunconn as wfc
from django import forms
from django.core.validators import MinValueValidator
from neuronsimulator.utils import WormfunconnToPlot as wfc2plot


class ParamForm(forms.Form):
    """
    This is a form class used for collecting parameters from POST or GET request to plot neural responses
    """

    stim_type_list = wfc2plot().get_stim_type_list()
    stim_type_choices = wfc2plot().get_stim_type_choice()

    form_opt_field_dict = wfc2plot().get_form_opt_field_dict()

    strains = wfc.strains

    STRAIN_CHOICES = [(strain, strain) for strain in strains]

    strain_type = forms.ChoiceField(
        choices=STRAIN_CHOICES,
        widget=forms.Select,
        label="Type of strain",
        initial="wild-type",
    )
    stim_type = forms.ChoiceField(
        choices=stim_type_choices,
        label="Activity waveform of stimulated neuron",
        initial="realistic",
        widget=forms.Select,
    )
    stim_neu_id = forms.ChoiceField()
    resp_neu_ids = forms.MultipleChoiceField()
    top_n = forms.IntegerField(
        initial=10,
        label="Top N most responsive",
        required=False,
        help_text="If not None, return top N responses with the largest absolute peak amplitude.",
        widget=forms.NumberInput(attrs={"min": 0}),
    )
    nt = forms.IntegerField(
        initial=1000,
        label="Number of time points",
        validators=[MinValueValidator(1)],
        widget=forms.HiddenInput(attrs={"min": 1}),
    )
    t_max = forms.FloatField(
        initial=100,
        label="Time window to plot (s)",
        validators=[MinValueValidator(0.1)],
    )
    # optional fields based on stim_types
    duration = forms.FloatField()
    frequency = forms.FloatField()
    phi0 = forms.FloatField()
    tau1 = forms.FloatField()
    tau2 = forms.FloatField()

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)
        # set attrs. for optional fields:
        for field_name, field_attrs in self.form_opt_field_dict.items():
            self.fields[field_name].label = field_attrs["label"]
            self.fields[field_name].initial = field_attrs["default"]
            self.fields[field_name].help_text = field_attrs["help_text"]
            self.fields[field_name].widget.attrs["min"] = field_attrs["min_val"]
            self.fields[field_name].widget.attrs["max"] = field_attrs["max_val"]
            self.fields[field_name].widget.attrs["step"] = field_attrs["step"]

        # default choices for neurons
        neuron_ids, app_error_dict = wfc2plot().get_neuron_ids("wild-type")
        # set neuron choices based on strain type
        if "strain_type" in self.data:
            try:
                strain_type = self.data.get("strain_type")
                neuron_ids, app_error_dict = wfc2plot().get_neuron_ids(strain_type)
            except (ValueError, TypeError):
                neuron_ids, app_error_dict = wfc2plot().get_neuron_ids("wild-type")

        neuron_choices = [(neu_id, neu_id) for neu_id in neuron_ids]

        self.fields["stim_neu_id"] = forms.ChoiceField(
            choices=neuron_choices,
            required=False,
            label="Stimulated neuron",
            widget=forms.Select(
                attrs={
                    "class": "selectpicker",
                    "data-live-search": "true",
                    "data-width": "fit",
                    "title": "Choose one neuron",
                }
            ),
        )

        self.fields["resp_neu_ids"] = forms.MultipleChoiceField(
            choices=neuron_choices,
            label="Hand selected neurons",
            required=False,
            widget=forms.SelectMultiple(
                attrs={
                    "class": "selectpicker",
                    "data-live-search": "true",
                    "data-width": "fit",
                    "data-actions-box": "true",
                    "data-selected-text-format": "count > 12",
                    "title": "Choose neurons a priori",
                }
            ),
        )

        self.fields["top_n"].widget.attrs["max"] = len(neuron_ids) - 1

neuronsimulator/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse
from neuronsimulator.forms import ParamForm
from neuronsimulator.utils import WormfunconnToPlot as wfc2plot


def home(request):

    context = {}
    form_init_dict = {}
    form_params = {}
    plot_div = {}
    resp_msg = ""
    url_for_plot = ""
    code_snippet = ""
    app_error_dict = {}
    # form_opt_field_dict = {}
    form_opt_field_init_dict = {}

    # get initial values for all form fields
    my_form = ParamForm()
    for k in my_form.fields.keys():
        form_init_dict[k] = my_form[k].initial

    # get initial values and associated stim_type for optional form fields
    form_opt_field_dict = my_form.form_opt_field_dict
    for k, v in form_opt_field_dict.items():
        v2 = {k1: v1 for k1, v1 in v.items() if k1 in ["stim_type", "default"]}
        form_opt_field_init_dict[k] = v2

    # get the list of names for optional fields
    opt_field_names = list(form_opt_field_dict.keys())

    # get form input from request
    if request.method == "POST":
        my_form = ParamForm(request.POST)
    elif request.method == "GET":
        input_params_dict = dict(request.GET)
        # value in list type, convert to string except for resp_neu_ids
        for key, value in input_params_dict.items():
            if key != "resp_neu_ids" and value != ["None"]:
                input_params_dict.update({key: str(value[0])})
            elif value == ["None"]:
                input_params_dict[key] = None
        # merge to get all form fields, input_params_dict have priority in terms of values
        form_data_dict = {**form_init_dict, **input_params_dict}
        my_form = ParamForm(form_data_dict)

    # get form error dict
    form_errors = my_form.errors.as_data

    # get form valid input values
    form_params = my_form.cleaned_data

    if my_form.is_valid():
        # get all output for neural response plot, and write error(s) to app_error_dict
        out = wfc2plot().get_all_output_for_plot(form_params)
        plot_div = out.plot_div
        resp_msg = out.resp_msg
        code_snippet = out.code_snippet
        app_error_dict = out.app_error_dict

        # get url for plot
        url_for_plot = (
            request.build_absolute_uri("/")[:-1]
            + reverse("home")
            + "?"
            + out.url_query_string
        )

        # add all output to context
        context = {
            "form": my_form,
            "form_opt_field_init_dict": form_opt_field_init_dict,
            "opt_field_names": opt_field_names,
            "form_errors": form_errors,
            "app_error_dict": app_error_dict,
            "resp_msg": resp_msg,
            "plot_div": plot_div,
            "url_for_plot": url_for_plot,
            "code_snippet": code_snippet,
        }
    else:
        # for invalid form, render valid form values in addition to form error(s)
        my_form = ParamForm(form_params)
        context = {
            "form": my_form,
            "form_opt_field_init_dict": form_opt_field_init_dict,
            "opt_field_names": opt_field_names,
            "form_errors": form_errors,
        }

    return render(request, "home.html", context)


def load_neurons(request):
    strain_type = request.GET.get("strain_type")
    neuron_ids, app_error_dict = wfc2plot().get_neuron_ids(strain_type)
    response_data = {"neurons": neuron_ids}
    return JsonResponse(response_data)

FuncAtlas/templates/base.html
{% load static %}
<!--use Bootstrap CSS and JS 5.0.1-->
<!--https://getbootstrap.com/docs/5.0/getting-started/download/-->
<!doctype html>
<html lang="en-US">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="{% static 'bootstrap-5.0.1-dist/css/bootstrap.css' %}" rel="stylesheet">

         <!-- Custom styles for this template -->
        <link href="{% static 'css/sidebar.css' %}" rel="stylesheet">
        <link href="{% static 'css/extras.css' %}" rel="stylesheet">

        <title>{% block title %}NeuroSimulator{% endblock %}</title>
    </head>

    <body>

    {% include 'navbar.html' %}

        <div class="container-fluid">
                {% block content %}
                {% endblock %}
        </div>

        <!-- Use Bootstrap JS -->
        <script src="{% static 'bootstrap-5.0.1-dist/js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

FuncAtlas/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div>
    <h3>NeuroSimulator Dashboard</h3>
    <br>
    <h5>Note: placeholder; will add contents later</h5>
</div>
{% endblock %}

FuncAtlas/templates/navbar.html
{% load static %}

<!-- Navbar -->
<!--ref:  https://getbootstrap.com/docs/5.0/components/navbar/-->
<nav class="navbar navbar-expand-md navbar-light" style="background-color: #eee8c0cb;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'images/logo.png' %}" alt="Icahn Laboratory" width="30" height="24">
            NeuroSimulator
        </a>

        <ul class="navbar-nav me-auto">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown-list-data" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Run Program
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown-download-data" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Download Data
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdown-download-data">
                    <li><a class="dropdown-item" href="#">Neuro Functional Atlas</a></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown-help" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Help
                </a>
            </li>
        </ul>

        <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Text Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

    </div>
</nav>

neuronsimulator/templates/base.html
{% load static %}
<!doctype html>
<html lang="en-US">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS 5.0.2-->
        <!--https://getbootstrap.com/docs/5.0/getting-started/download/-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
            rel="stylesheet" 
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
            crossorigin="anonymous">

        <!--Font Awesome-->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
            integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
            crossorigin="anonymous">
        
        <!-- bootstrap-select 1.14.0-beta2 minified CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta2/dist/css/bootstrap-select.min.css">

         <!-- Custom styles for this template -->
        {% block head_extras %}
        {% endblock %}

        <title>{% block title %}FunSim (Beta){% endblock %}</title>
    </head>

    <body>

    {% include 'navbar.html' %}

        <div class="container-fluid" id="con1">
            {% block content %}
            {% endblock %}
        </div>

        <!-- jQuery JS -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" 
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" 
            crossorigin="anonymous">
        </script>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
            crossorigin="anonymous">
        </script>

        <!-- bootstarp-select 1.14.0-beta2 compiled and minified JavaScript -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta2/dist/js/bootstrap-select.min.js"></script>

        <!-- additional JS -->
        {% block js_extras %}
        {% endblock %}
    </body>
</html>

neuronsimulator/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}FunSim{% endblock %}

{% block head_extras %}
    {{ block.super }}
    <style>
        #div1 {
            background-color: #f0ebcccb;
        }
    </style>

    <!--form initial values for optional fields-->
    {{ form_opt_field_init_dict|json_script:"form_opt_field_init_dict" }}

    <script>
        // Initialize Bootstrap Tooltips
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl)
        })

        // get names and initial values for optional fields
        var form_opt_field_init_dict = JSON.parse(document.getElementById('form_opt_field_init_dict').textContent);

        function showField(field_name) {
            let div_id = 'div_' +  field_name;   
            document.getElementById(div_id).style.display='block';
        }

        function hideField(field_name) {
            let div_id = 'div_' +  field_name;
            document.getElementById(div_id).style.display='none';
        }

        function showHideFormFields() {
            // get value for stim_type
            let stim_type_value = document.getElementById("id_stim_type").value;
            let sel_option = document.getElementById("id_stim_type").selectedOptions;

            Object.entries(form_opt_field_init_dict).forEach((entry) => {
            let [field_name, field_attrs] = entry;
            if ( field_attrs["stim_type"] === stim_type_value) {
                showField(field_name);
            } else {
                hideField(field_name);
            }
            });
        }

        document.addEventListener("DOMContentLoaded",function() {
            showHideFormFields()
        })

        function emptyOutput() {
            // empty output section
            document.getElementById("div_output").innerHTML = "";
        }

        function setTopNToNone() {
            // set top_n to None
            document.getElementById("id_top_n").value = "";

        }

        function setRespNeuIDsToNone() {
            // set resp_neu_ids to None
            $('#id_resp_neu_ids').selectpicker('val', 'deselectAll');
        }

        function setNeuronChoices() {
            var url = $("#form").attr("data-neurons-url");
            $.ajax({
                async: false,
                type: 'GET',
                url: url,
                data:{
                    strain_type: $("#id_strain_type").val(),
                },
                dataType: 'json',
                success: function(data) {
                    var ele1 = document.getElementById("id_stim_neu_id");
                    var ele2 = document.getElementById("id_resp_neu_ids");
                    var ele3 = document.getElementById("id_top_n");
                    // remove all options
                    ele1.options.length = 0;
                    ele2.options.length = 0;
                    // create new option element
                    for(var i=0; i < data.neurons.length; i++)
                    {
                        var option = document.createElement("option");
                        // console.log(data.neurons[i])
                        option.innerHTML = '<option value="' + data.neurons[i] + '">' + data.neurons[i] + '</option>';
                        ele1.innerHTML += option.innerHTML
                        ele2.innerHTML += option.innerHTML
                    }
                    // set top_n max and default values
                    ele3.setAttribute("max", data.neurons.length -1);
                    ele3.setAttribute("value", 10);
                }
            });
            // refresh select options
            $('#id_stim_neu_id').selectpicker('refresh');
            $('#id_stim_neu_id').selectpicker('');
            $('#id_resp_neu_ids').selectpicker('refresh');
            $('#id_resp_neu_ids').selectpicker('deselectAll');
        }

        function reset_form() {
            let text = "Are you sure you want to discard selected parameters for plotting and start over?"
            if (confirm(text) == true) {
                window.location = window.location.pathname
            }
            else {
                return None;
            }
        }
    </script>
{% endblock %}

{% block content %}
<div id="intro">
    <!--Webpage introduction -->
    <p>
        This web-app allows you to simulate responses of downstream neurons to
        the stimulation of other neurons using the functional connectivity data
        measured by <a
        href="https://www.nature.com/articles/s41586-023-06683-4">Randi et al.,
        Nature (2023)</a>, measured via simultaneous single-cell optogenetics and
        whole-brain imaging.
    </p>
    <p>
        To start, select a neuron to be stimulated and the activity that you want
        to be induced in that neuron (irrespectively of the method of stimulation).
        The "realistic" activity type is an empirical representative activity transient
        following a stimulus, whose shape and duration can be tuned with the two timescales.
        Then select either the neurons whose responses you'd like to plot or the top n most
        responsive neurons.
    </p>
    <p>
        <a href="https://github.com/Princeton-LSI-ResearchComputing/funsim"> FunSim web-app</a>
        is an interface to the
        <a href="https://www.github.com/leiferlab/worm-functional-connectivity">
        Worm Functional Connectivity</a> python library that is available on Github.
        At the bottom of the plot, you can obtain the code snippet to replicate the plot
        on your computer.
    </p>
</div>
<br>
<div class="row" id="div0">
    <div class="col-sm-4" id="div1">
        {% if form %}
            <form action="/neuronsimulator/" method="POST" id="form" 
                data-neurons-url="{% url 'load_neurons' %}">
               {% csrf_token %}
                <!--handle errors-->
                {% if form.errors %}
                    <!--non-field errors-->
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                {% endif %}
                 <!--hidden fields-->
                 {% for hidden_field in form.hidden_fields %}
                        {% if hidden_field.errors %}
                            <div class="alert alert-danger">{{ hidden_field.errors }}</div>
                        {% endif %}
                        {{ hidden_field }}
                {% endfor %}
                <!--non-hidden fields-->
                <!--Which Strain-->
                <br>
                <div id="div_strain_type" style="display:block" class="form-control" 
                    onchange="setNeuronChoices();emptyOutput()">
                    <label>{{ form.strain_type.label }}</label>
                    {{ form.strain_type.errors }}
                    {{ form.strain_type }}
                </div>
                <br>
                <!--render the fields manually and set display for each field based on inital stim_type-->
                <div id="div_stim_neu_id" style="display:block">
                    <label class="fw-bold text-danger">{{ form.stim_neu_id.label }}</label>
                    {{ form.stim_neu_id.errors }}
                    {{ form.stim_neu_id }}
                </div>
                <br>
                <div id="div_stim_type" class="form-control"
                    onchange="showHideFormFields(); emptyOutput()">
                    <label>{{ form.stim_type.label }}</label>                   
                    {{ form.stim_type.errors }}
                    {{ form.stim_type }}
                </div>
                <br>
                <p>Activity waveform temporal shape
                <i class="far fa-question-circle" data-bs-toggle="collapse" data-bs-target="#waveform_helptext"></i>
                </p>
                    <div class="collapse" id="waveform_helptext">
                        <div class="card card-body">
                            <p>For "realistic" activity type, timescale 1 and 2 are the timescales of
                                the two decaying exponentials whose difference is the activity waveform.
                            </p>
                        </div>
                    </div>
                <!-- optional fields-->
                {% for field in form.visible_fields %}
                    {% if field.name in opt_field_names %}
                        <div id="div_{{ field.name }}" style="display:none" class="form-control">
                            <label id="label_for_{{ field.name }}" for="{{ field.name }}">{{ field.label }}</label>
                            {{ field.errors }}
                            {{ field }} &nbsp;&nbsp;
                            <i class="far fa-question-circle" data-bs-toggle="collapse" data-bs-target="#id_{{ field.name }}_helptext"></i>
                            <div class="collapse" id="id_{{ field.name }}_helptext">
                                <div class="card card-body">{{ field.help_text }}</div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
                <!--responding neurons-->
                <br>
                <p> Select neurons to plot:
                <i class="far fa-question-circle" data-bs-toggle="collapse" data-bs-target="#id_resp_helptext"></i>
                </p>
                    <div class="collapse" id="id_resp_helptext">
                        <div class="card card-body">
                            <p>Selecting one or multiple response neurons will automatically deselect top N value. 
                                Entering a value for top N and deselect all response neuron(s), top N responses will 
                                be plotted. The default value for Top N is 10. Unselecting both response neurons and top N 
                                will plot responses based on default threshold value.
                            </p>
                        </div>
                    </div>
                <div id="div_resp_neu_ids" style="display:block" onclick="setTopNToNone()"> 
                    <label>{{ form.resp_neu_ids.label }}</label>
                    {{ form.resp_neu_ids.errors }}
                    {{ form.resp_neu_ids }}
                </div>
                <p class="fw-bold text-danger">or</p>
                <div id="div_top_n">
                    <label>{{ form.top_n.label }}</label>
                    {{ form.top_n.errors }}
                    {{ form.top_n }}&nbsp;&nbsp;
                    <i class="far fa-question-circle" data-bs-toggle="collapse" data-bs-target="#id_top_n_helptext"></i>
                    <div class="collapse" id="id_top_n_helptext">
                        <div class="card card-body">{{ form.top_n.help_text }}</div>
                    </div>
                </div>
                <br>
                <div id="div_t_max" class="form-control" style="display:block">
                    <label>{{ form.t_max.label }}</label>
                        {{ form.t_max.errors }}
                        {{ form.t_max }}
                </div>
                <br>
                <div class="row">
                    <div class="col">
                        <input id="button_startover" style="display:block" type="button"
                            onclick="reset_form()"
                            value="Clear All" class="btn btn-outline-primary">
                    </div>
                    <div class="col">
                        <input id="button_submit" style="display:block" type="submit"
                            value="Plot" class="btn btn-lg btn-primary">
                    </div>
                </div>
                <div class="row">
                    <p class="text-danger">Note: please select at least a stimulated neuron before plotting</p>
                </div>
            </form>
        {% endif %}
    </div>
    <div id="div_output" class="col-sm-8" style="display:block">
        {% include "output_params_plot.html" %}
    </div>
</div>

{% endblock %}

neuronsimulator/templates/navbar.html
{% load static %}

<!-- Navbar -->
<!--ref:  https://getbootstrap.com/docs/5.0/components/navbar/-->
<nav class="navbar navbar-expand-md navbar-light" style="background-color: #eee8c0cb;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'images/logo1.png' %}" alt="Icahn Laboratory" width="40" height="40">
           FunSim
        </a>

        <ul class="navbar-nav me-auto">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarLinks" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Links
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarLinks">
                  <li><a class="dropdown-item" href="https://elegans.princeton.edu/">Leifer Lab Tools</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="https://github.com/Princeton-LSI-ResearchComputing/funsim">FunSim@GitHub</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="https://github.com/leiferlab/worm-functional-connectivity">Worm Functional Connectivity</a></li>
                </ul>
              </li>
        </ul>
    </div>
</nav>